FROM ubuntu:focal-20220801

RUN apt-get update && apt-get install -y \
	curl \
	ca-certificates \
	gnupg \
	dos2unix \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_21.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update && apt-get install -y \
	nodejs \
	&& rm -rf /var/lib/apt/lists/*

RUN useradd golem -m

RUN mkdir /home/golem/app
COPY start.sh /home/golem/start.sh
RUN dos2unix /home/golem/start.sh
RUN chmod +x /home/golem/start.sh
RUN chown -R golem:golem /home/golem

USER golem
WORKDIR /home/golem/

ENV PATH=${PATH}:/usr/bin

EXPOSE 3000

ENTRYPOINT ["/home/golem/start.sh"]