version: '3.7'
services:
  requestor:
    build:
      dockerfile: Dockerfile_requestor
      context: .
    image: maugnorbert/requestor:0.14.0
    volumes:
      - yagna-bin:/yagna/bin
      - /home/${USER}/.local/share/yagna:/root/.local/share/yagna
    environment:
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465
      - GOERLI_GETH_ADDR=https://rpc.ankr.com/eth_goerli
    restart: unless-stopped
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: mydb
    restart: unless-stopped
  backend:
    build:
      dockerfile: Dockerfile_backend_web_gpu_rendering
      context: .
    image: maugnorbert/backend_web_gpu_rendering
    links:
      - db
      - requestor
    ports:
      - 3001:3001
    volumes:
      - yagna-bin:/home/golem/yagna
      - ./backend_web-gpu-rendering:/home/golem/app
    environment:
      - HOST_BACKEND=db
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - GSB_URL=tcp://requestor:7464
      - YAGNA_API_URL=http://requestor:7465
    restart: unless-stopped
  frontend:
    build:
      dockerfile: Dockerfile_frontend_web_gpu_rendering
      context: .
    image: maugnorbert/frontend_web_gpu_rendering
    ports:
      - 3000:3000
    volumes:
      - ./frontend_web-gpu-rendering:/home/golem/app
    restart: unless-stopped
volumes:
  yagna-bin:
    driver: local